export const genreEquivalents = [
  {
    name: "Action & Adventure",
    equivalents: [
      "Acción",
      "Aventura",
      "Superheroes",
      "Heroica",
      "Epica",
      "Batallas",
      "Epicas",
    ],
  },
  {
    name: "Animation",
    equivalents: [
      "Animación",
      "Animada",
      "Infantil",
      "Dibujos animados",
      "Dibujos",
      "Dibujo",
      "Dibujada",
      "Dibujadas",
      "Dibujado",
      "Dibujados",
      "Disney",
      "Pixar",
      "Dreamworks",
      "Animé",
      "Anime",
      "Cartoon",
      "Cartoons",
      "Superheroes",
      "Animacion 3D",
    ],
  },
  {
    name: "Comedia",
    equivalents: [
      "Comedy",
      "Divertida",
      "Graciosa",
      "Risas",
      "Cómica",
      "Humor",
      "Humorística",
      "Divertidas",
      "Graciosas",
      "Cómicas",
      "Humorísticas",
      "Divertidos",
      "Graciosos",
      "Cómicos",
      "Humorísticos",
      "Parodia",
      "Satira",
      "Burlesca",
    ],
  },
  {
    name: "Crimen",
    equivalents: [
      "Crime",
      "Policial",
      "Detective",
      "Investigación",
      "Investigativa",
      "Investigativo",
      "Investigativos",
      "Investigativas",
      "Policíaca",
      "Policíaco",
      "Policíacas",
      "Policíacos",
      "Policiales",
      "Policíacos",
      "Detectives",
      "Criminal",
      "Criminales",
      "Criminalistica",
      "Crimen Real",
      "Thriller Policial",
      "Noir",
    ],
  },
  {
    name: "Documental",
    equivalents: [
      "Documentary",
      "Documentales",
      "Documentales de",
      "Documentales sobre",
      "Documentales acerca de",
      "Docudrama",
      "Biografia",
      "Autobiografica",
      "Autobigrafia",
      "Naturalista",
      "Autobiografias",
    ],
  },
  {
    name: "Mystery",
    equivalents: [
      "Misterio",
      "Intriga",
      "Enigma",
      "Enigmas",
      "Misteriosa",
      "Misteriosas",
      "Misterioso",
      "Misteriosos",
      "Intrigante",
      "Intrigantes",
      "Enigmática",
      "Enigmáticas",
      "Enigmático",
      "Enigmáticos",
      "Thriller",
      "Investigacion Paranormal",
    ],
  },
  {
    name: "Reality",
    equivalents: ["Competicion", "Docu-reality", "Telerrealidad"],
  },
  {
    name: "Fantasy",
    equivalents: [
      "Fantasía",
      "Fantasia",
      "fantasia",
      "Fantasiosa",
      "Fantasías",
      "Fantasiosas",
      "Fantasioso",
      "Fantasiosos",
      "Fantástica",
      "Fantásticas",
      "Fantástico",
      "Fantasía épica",
      "Fantasías épicas",
      "Fantasía medieval",
      "Fantasías medievales",
      "Fantasía oscura",
      "Fantasías oscuras",
      "Fantasía urbana",
      "Fantasías urbanas",
      "Fantasía de",
      "Fantasías de",
      "Superheroes",
      "Ficcion magica",
      "Cuento de hadas",
      "Cuentos de hadas",
      "Fantasia heroica",
      "Magos",
      "Hechiceros",
    ],
  },
  {
    name: "War & Politics",
    equivalents: [
      "Bélica",
      "Bélicas",
      "Bélico",
      "Bélicos",
      "Guerra",
      "Guerras",
      "Política",
      "Políticas",
      "Político",
      "Políticos",
      "Guerra y política",
      "Guerras y política",
      "Guerra y político",
      "Guerras y político",
      "Bélica y política",
      "Bélicas y política",
      "Bélico y político",
      "Bélicos y político",
      "Guerra mundial",
      "Guerra fria",
      "Guerras mundiales",
      "Conflicto belico",
      "Thriller politico",
    ],
  },
  {
    name: "Horror",
    equivalents: [
      "Terror",
      "Terrorífica",
      "Terroríficas",
      "Terrorífico",
      "Terroríficos",
      "Horror",
      "Horrorífica",
      "Horroríficas",
      "Horrorífico",
      "Horroríficos",
      "Horrorosa",
      "Horrorosas",
      "Horroroso",
      "Horrorosos",
      "Miedo",
      "Sobrenatural",
      "Sobrenaturales",
      "Gore",
      "Slasher",
    ],
  },
  {
    name: "Thriller",
    equivalents: [
      "Suspense",
      "Terror",
      "Terrorífica",
      "Terroríficas",
      "Terrorífico",
      "Terroríficos",
      "Horror",
      "Horrorífica",
      "Horroríficas",
      "Horrorífico",
      "Horroríficos",
      "Horrorosa",
      "Horrorosas",
      "Horroroso",
      "Horrorosos",
      "Suspenso",
      "Miedo",
    ],
  },
  {
    name: "Drama",
    equivalents: ["Drama", "Melodrama", "Tragedia", "Dramedia"],
  },
  {
    name: "Family",
    equivalents: [
      "Familia",
      "Familiar",
      "Familias",
      "Familiares",
      "Infantil",
      "Infantiles",
      "Niños",
      "Niñas",
      "Niñez",
      "Infancia",
      "Infantilidad",
      "Infantilidades",
      "Familiaridad",
      "Familiaridades",
      "Familiarismo",
      "Familiarismos",
      "Familiaridad",
      "Familiaridades",
      "Familiera",
      "Familieras",
      "Pelicula familiar",
      "Peliculas familiares",
      "Comedia familiar",
      "Aventura familiar",
    ],
  },
  {
    name: "History",
    equivalents: [
      "Historia",
      "Histórica",
      "Históricas",
      "Histórico",
      "Históricos",
    ],
  },
  { name: "Music", equivalents: ["Música", "Musical", "Opera", "Concierto"] },
  { name: "Romance", equivalents: ["Romance", "Amor", "Amorosa"] },
  {
    name: "Sci-Fi & Fantasy",
    equivalents: [
      "Ciencia ficción",
      "Ficción",
      "Ciencia",
      "Futurista",
      "Futuristas",
      "Futurístico",
      "Futurísticos",
      "Futurística",
      "Futurísticas",
      "Futurismo",
      "Futurismos",
      "Superheroes",
      "Espacial",
    ],
  },
  { name: "TV Movie", equivalents: ["Película de TV", "Miniserie"] },
  {
    name: "Western",
    equivalents: [
      "Western",
      "Oeste",
      "Viejo Oeste",
      "Vaqueros",
      "Vaquero",
      "Cowboy",
      "Cowboys",
      "Cowgirl",
      "Cowgirls",
    ],
  },
];